### ISSUE TITLE
feat: dkn in docker

### ISSUE THREAD

**Issue by chilljello** [firstbatchxyz/dkn-compute-node#152]
### Motivation

I am trying work on the docker container with DKN that will able to use the container from ollama and other resources. 

We need to build a script that work with these feature that also enable connect the internet via sock5 and https protocol.

work in progress.

```

services:
    dknmine:
      image: whatwhat/dkn-compute-node:latest 
      container_name: dkn_compute
      environment:
        - 'DKN_WALLET_SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxx'
        - 'http_proxy=http://host.docker.internal:7890'
        - 'https_proxy=http://host.docker.internal:7890'
        - 'all_proxy=socks5://host.docker.internal:7891'
      extra_hosts:
         - "host.docker.internal:host-gateway"
         - "0.0.0.0:127.0.0.1"
      volumes:
        - /srv/dkn:/dkn:rw
      working_dir: /workspace
      ports:
        - "19880:9880"
      shm_size: 16G
      deploy:
        resources:
          reservations:
            devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]
      stdin_open: true
      tty: true
      restart: unless-stopped
      networks:
        - nvidanetgroup
    ollama:
        volumes:
          - /srv/models/ollama:/root/.ollama
        container_name: ollama
        pull_policy: if_not_present
        tty: true
        restart: unless-stopped
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        networks:
          - nvidanetgroup
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]
volumes:
  valkey_data2:
networks:
  nvidanetgroup:
    name: mlnetgroup
    external: true
```
